name: Release Publication
on:
  release:
    types:
      - edited
      - published

permissions:
  contents: read
  id-token: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.8.1"
      - name: Install
        run: poetry build
      - name: Setup
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      - name: Publishers
        run: poetry publish