name: SonarCloud - Reports
'on':
  push:
    branches:
      - main

  # the following lines are mandatory for activating GitHub Pull Request Decoration
  # https://docs.sonarsource.com/sonarcloud/improving/pull-request-analysis/#pull-request-decoration
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  id-token: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.1
      - name: Install
        run: poetry install --with dev
      - name: Reporters
        run: make reporters
      - name: Report
        uses: SonarSource/sonarcloud-github-action@v2.1.1
Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Api
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /:
            get:
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true